### ISSUE TITLE
SoloSealVariations

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#13]
I have uploaded F2_Caprice.pdf to DropBox. Before I scan other solos, let's chat about how we are going to use the below stave information in Book 4.

**Comment by rsryman** [comment]
**TO BE DECIDED:** TOP VIEW (as in Ch 2) VERSUS BACK VIEW (as in Ch 3) 

I began creating an animation setting key frames for each location & direction faced listed in "CapriceTravel&FloorPlans.docx" with body shapes notated in "F2_Caprice.pdf." 
To display lines of travel in the Stage window, I select View > Paths. 

If decide to use a Top View animation, I need to address a problem:

**Problem:** To "correct" the perspective algorithm in the Performance window, I need to adjust the pelvis/torso orientations. What looks acceptable in the Stage window looks "off" in the Performance window (position and location).
**Solution:** I need to create 2 files: one that looks good in the Performance (for body shapes) window and one that looks good in the Stage window (for the Stage locations and lines of travel). OR Robyn to create the top view by superimposing arrows on the stage plan file as in Ch 3.

**Comment by rryman** [comment]
Rhonda, on Page 3 you have added the following:

"Chapter 6 brings together all theory introduced to this point by presenting a series of travelled sequences adapted from the Bournonville school* **and the RAD Solo Seal “Caprice” variation**.**"

We only have permission to use the below stave information from the RAD Solo Seal, so I am unclear what you have in mind here?

**Comment by rsryman** [comment]
Hard to envision how this might work. We could "quote" a few movements, no?
Let's defer this conversation until I meet wth Anuschka. Leave page 3
flagged as is until we decide?

**Comment by rsryman** [comment]
I have created a chart and stage plans for Caprice. See For Robyn > Caprice folder:
CapriceTravel&FloorPlansComments.docx 
CapriceStagePlansJuly2017.pdf  

We should discuss the "value added" in providing stage plans before we can decide how to proceed. It was an interesting exercise to compare the notated version with Anuschka's comments, Olivia Tracey's performance, and the dancer on the DVD. Bottom line, I think the stage plans could provide a very helpful summary/overview, supplementing the bar-by-bar notation score. A lot to discuss re how to break down and "recombine" the paths and label the stage plans, because the dance phrases and lines of travel overlap the musical bars. Never simple.

**Comment by rsryman** [comment]
We have decided to use limited stage plans re Caprice, not the specific contentious details Rhonda gleaned in the meeting with Anuschka and Olivia Tracey.
