### ISSUE TITLE
DanceForms Reminders

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#2]
1. If the timing goes askew, check that the Panel pointer is exactly centred, since DanceForms exports at the default frame rate not the Panel setting.
2. Be sure to add a second at the end so the dancer's final position is retained.

**Comment by rsryman** [comment]
See "StagePlanTemplate.lfa" created on new laptop May 20/17 by changing the dimension of the stage from 10x8 (which altered the aspect ratio of the original pdf "StagePlan.pdf") to 10x6 (which preserved the aspect ratio"). I was able to create a top view with the dancer positioned at 0, 0 (centre stage) by cropping the oblique lines at the "open" end of the stage plan (which DF calculated in the total depth of the stage and shifted middle upward).

I used this template to begin plotting the specific stage locations & directions in RAD Solo Seal "Caprice."

**Comment by rsryman** [comment]
A few more reminders:
1. In Book 4 I used a Stage Plan jpeg (created as a handout for Dance 241/341) to create guidelines on the DanceForms stage floor. As the book progressed, I realized that the aspect ratio (width:depth) was NOT the same as Robyn was using (based on the Benesh Encyclopaedia) to create stage plans in Adobe Illustrator for Ch 2 & 3. We therefore had to do substantial tweaking to make notations and animations conform.
2. Because of the DanceForms perspective algorithm, we decided to limit using Top view in the Performance Window (the dancer appeared off-vertical anywhere but centre centre stage). 
3. Because of the DanceForms perspective algorithm, stage dimensions appeared distorted in Back View. It was particularly difficult to judge how far the dancer moved upstage-downstage. This was compounded when we needed to zoom in to enlarge the figure in CH 5 & 6 (this cut off the horizontal upstage boundary of the stage plan that provided a reference point).
