### ISSUE TITLE
BB11 Proofreading

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#23]
**DONE** 

.iba file uploaded Monday March 27th, 2:36 PM

I have made the horizontal tick shorter and either joined the location signs or put them as close together as possible on pages 22, 24, 26, 28, and 31.
I have also added a note on page 22 and 24 about the location signs.

Please let me know if there are any errors in the stage plans or text, and if there are any edits you want made.

**Comment by rsryman** [comment]
See uploaded file: BalletBook4RR.iba

As discussed I used the most recent iba file to proofread BB11 up to p.33.

Tomorrow I'll look at pp. 33-34 of the Review you are working on. You also asked me to think about adding a question using an animation back view and drag labels in the order that matches locations. TO DO

**Comment by rsryman** [comment]
Since I couldn't edit the iba file on p. 34 (because it's a widget?), it 's simplest to give feedback here.
p. 33 I know you want to establish a “template” for wording the Review instructions; if so leave it as it was. This suggestion streamlines it a bit: "Reinforce your understanding and test your ability to read travel signs by doing the following review. This review contains three sections: the first contains ? questions, the second contains ? questions, and the section contains a maze puzzle."

p. 34:  Questions 2-5 are excellent. I just had a problem with Question 1 of 5: the wording of sentences 2-3 is a bit confusing. Maybe we can discuss this via Hangout.
Suggest adding after sentence 1 (if room): 
The tick is placed at the head of the arrow (either side) to indicate [travel forward/back].
The tick is placed at the tail of the arrow (either side) to indicate [travel sideways].
Then go on  with your sentences 2-3:
The placement of the tick at either the head or tail of the shaft indicates [direction of travel].
The placement of the tick on either side of the head or tail of the shaft of the arrow indicates [direction faced] while travelling.
OR MAYBE: 
The end at which the tick is placed indicates [direction faced] while travelling.
The side on which the tick is placed indicates [direction faced] while travelling.

Question 2 of 5 is clear (just change "the tick" to "a tick" in the bottom sentence?) 
Questions 3-5 of 5 are great.
In Question 5 of 5, can you lower the buttons to separate them from the stage plan so they are not visually connected with it (just sequence in time not location re stage plan)?

After we talk about Question 1 of 1, maybe we can discuss ideas for the p. 35 question.

**Comment by rryman** [comment]
Page 24. I think your suggested edit changes the meaning.

Original: Remember to think of the tick indicating the direction of travel as representing the right shoulder (in this case, your back is to the direction of travel).

Your suggestion:
Remember to think of the tick indicating the direction of travel as representing the right shoulder (in travel backward, your back is to the direction of travel).

**Comment by rryman** [comment]
Page 32 diagonal arrows. Sorry I can't match the diagonal back-right colour. I darkened the diagonal front-left as you suggested. I made the diagonal back-right more greenish so the two colours will look more different. As soon as I paste your png of the back-right DF figure into Adobe Illustrator it completely changes its colour. The vibrant colour goes dull, so I can't use the "eye-dropper" to match it.

**Comment by rryman** [comment]
Please rewrite this question for me in the following format:
To fit on the area of the review widget, or broken into two pages.
There can only be (at most) 6 unique labels per question.

---

p. 34: Questions 2-5 are excellent. I just had a problem with Question 1 of 5: the wording of sentences 2-3 is a bit confusing. Maybe we can discuss this via Hangout.
Suggest adding after sentence 1 (if room):
The tick is placed at the head of the arrow (either side) to indicate [travel forward/back].
The tick is placed at the tail of the arrow (either side) to indicate [travel sideways].
Then go on with your sentences 2-3:
The placement of the tick at either the head or tail of the shaft indicates [direction of travel].
The placement of the tick on either side of the head or tail of the shaft of the arrow indicates [direction faced] while travelling.
OR MAYBE:
The end at which the tick is placed indicates [direction faced] while travelling.
The side on which the tick is placed indicates [direction faced] while travelling.

**Comment by rsryman** [comment]
P. 34 Question 1 of 5, suggestion re sentences 2-3:
Look at the placement of the tick at the head or the tail to determine the [direction of travel].
Look at the placement of the tick on one side or the other to determine the [direction faced] while travelling.

**Comment by rryman** [comment]
How do you feel about combining these two sentences as both pieces of information are technically necessary to determine the direction of travel?
Would it read okay to say:

**Look at the placement of the tick at the head or the tail to determine the [direction of travel] and
the placement of the tick on one side or the other to determine the [direction faced] while travelling.**

**Comment by rsryman** [comment]
Yes, this works.

Can you do anything with layout to offset the points, e.g.:







*Look at the placement of the tick - -  at the head or the tail to
determine the [direction of travel] and -  on one side or the other to
determine the [direction faced] while travelling. If this doesn't work, I'm
fine to go with the sentence you suggested.*

**Comment by rryman** [comment]
Rhonda you haven't responded to this yet:

Page 24. I think your suggested edit changes the meaning.

Original: Remember to think of the tick indicating the direction of travel as representing the right shoulder (in this case, your back is to the direction of travel).

Your suggestion:
Remember to think of the tick indicating the direction of travel as representing the right shoulder (in travel backward, your back is to the direction of travel).

What about changing it to be more inline with page 26?
Remember to think of the tick indicating the direction of travel as representing the right shoulder (i.e., with the body facing toward the shaft and the back to the direction of travel).

**Comment by rryman** [comment]
Nor this:
Page 32 diagonal arrows. Sorry I can't match the diagonal back-right colour. I darkened the diagonal front-left as you suggested. I made the diagonal back-right more greenish so the two colours will look more different. As soon as I paste your png of the back-right DF figure into Adobe Illustrator it completely changes its colour. The vibrant colour goes dull, so I can't use the "eye-dropper" to match it.

**Comment by rsryman** [comment]
Proofreading BB11 (I'll proofread the Reviews under separate issues):
√pages 22, 24, 26, 28, and 31 (now 23, 25, 29, 31); size of ticks and locations signs
√page 22 and 24 (now 23 and 25): footnote added about joining/separating composite location signs
√page 24: Remember to think of the tick indicating the direction of travel as representing the right shoulder (i.e., with the body facing toward the shaft and the back to the direction of travel).

p. 32 still to be discussed: I think we need to try something else for the back diagonal right arrow or figure because they really don't match. When you get a chance, look at page 30: if you can suggest a colour between the yellow (back) and green (side right) that Adobe Illustrator can handle, I'll try to match it in the DanceForms colour palette and change the images and animations.

**Comment by rryman** [comment]
Before I change the colours of the arrows in Illustrator, can we agree that backward-left is yellow + blue = green; and backward-right is yellow + green = lime green? Therefore can we choose a darker green for backward-left and a lime green for backward-right so the two colours look significantly different? I guess they also both need to be a different green from the one you used for sideways right. Illustrator doesn't appear to handle the luminous colours so they are not a good choice.

**Comment by rsryman** [comment]
Just heading out but back in an hour. Can we do a Hangout to decide?

**Comment by rryman** [comment]
Let me know what time you want to do a hangout.

**Comment by rryman** [comment]
Here is what we have decided via phone call:
![diagonaltravelarrows](https://cloud.githubusercontent.com/assets/15850667/24839389/6884c390-1d27-11e7-8bbe-e06b5cc2d787.jpeg)

**Comment by rsryman** [comment]
I decided to make sure the updated colours would work with all direction.
See uploaded file re p. 30: Travel8Directions+.m4v and Travel8Directions++.m4v

Call and I'll talk you through if this description is too convoluted.

Re Travel8Directions+.m4v: After playing with the colours as best I could, I was able to match your arrow for back left (Moss). But then the domino effect happened: the only darker green (Moss) I could find for back right was too similar to the green (Clover) for side right, so I changed that to the darkest blue (Midnight) I could find, which was too close to the forward left purple (Eggplant), so I had to change that to Plum. For the record, the colours in the uploaded animation are:

Forward (Marischino), Back (Lemon); Side Left (Blueberry); Side Right (Midnight); Forward Right (Mocha); Forward Left (Plum); Back Right (Asparagus); Back Left (Moss).

Re Travel8Directions++.m4v: In case you think that Blueberry and Midnight blue are too similar re side right/left (pp. 26-29), I also tried a lighter blue for side left (Aqua).

If you can match these colours for your arrows on p. 32 and agree to this colour scheme, go ahead and update p. 30. I will then update 3 png files for p. 31, the animation on p. 32, the animations on pp. 26-27 (green->Midnight blue) and, if needed, the animation on pp 28-29 (Blueberry -> Aqua).

**Comment by rryman** [comment]
Here it is:
![diagonalarrowcolours](https://cloud.githubusercontent.com/assets/15850667/24925114/3851e69a-1ec5-11e7-81ef-cd0ec3a7d655.jpeg)

Once you approve the colours of the arrows, I will update the stage plan graphic on page 27 and on page 32.

**Comment by rsryman** [comment]
In rereading the book to start writing Chapter 1, I now question the title and footnote for p. 30: "Travel Diagonally." Perhaps we want to say:  Between the four main directions of travel (forward, backward side right, and side left) are four diagonal directions:…

Since the page is titled "Travel Diagonally," perhaps the 4 newly introduced travel signs in the graphic could be highlighted somehow (make the forward, backward side right, and side left signs grey instead of black??).

Also the footnote doesn't relate to the info in the Appendix p. 48 "More Examples of Diagonal Travel." Don't we mean: Each of the four diagonal directions of travel may be performed along the eight basic lines of travel. The full set of 32 diagonal travel signs is illustrated in Appendix ??.

**Comment by rryman** [comment]
I have made the updates that you mentioned above - except I think it should be **(forward, sideways right, backward, sideways left)** to be consistent with what we call sideways travel on the previous pages,

**Comment by rryman** [comment]
Rhonda:
Just a thought, but we might need to more clearly distinguish between "direction of travel" (relating to the dancer) first mentioned on p. 22, and "line of travel" (relating to the stage) first mentioned on p. 20. Perhaps in Ch 1, restated on p. 21 (which is what I was getting at in the footnote).

Robyn: I don't know what you want me to do with this comment.
