### ISSUE TITLE
Rhonda'sCommentsOnBookSentToReaders

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#31]
**DONE**
I will compile a running commentary of things I find as I go through the book. 
I will communicate important items to our readers but some details are just for us to discuss/update.

p. 40: I think we should capitalize the second word in a hyphenated title:
Stage Plans and Multi-Stave Scores (also on p. 41)
Multi-Dancer Dance Scores (take out the red link since that page is not in this draft)
Check that you can get back to this page from each of the pages in the Appendix (link as on p. 43 is missing on some pages, perhaps because there is no room?)

**Comment by rryman** [comment]
I had to "Reset for iBooks Store" so Eliane wouldn't have trouble with seeing the incorrect cover. I believe this is what fixed the problem when it occurred last time. I corrected the above comments. However, I had to take out "Go Back To" in the links so that everything would fit. Hopefully by the time people get to the Appendix, they will understand how the top links work. It was the best fix I could devise. I will upload the updated version of the book to dropbox before sharing it with Carla and Liz. I will reshare it with Ros and Eliane.
