### ISSUE TITLE
Feedback - Liz

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#79]
Liz's comments below are based on the old version of Book 4 with only 3 chapters.

Below, I have used the page numbers relevant to our latest Book 4 with 9 chapters and 134 pages.

My comments are in [bold] under Liz's comments.

- [x] P6:  Note at bottom of the page: ‘Primarily British usage – I cannot see what this is cross referencing to.
**[Prompt and Opposite Prompt were removed from the diagram captions, so this comment is no longer relevant.]** 

- [x] P12:	I’m finding the stage plan figures hard to recognize – I’m on an ipad mini, they may read better on a full sized ipad.  For instance Anna looks as if she has 3 heads and Jenna two.
**[These were changed to x's, so this should be no longer a problem.]**

- [x] P12, 13, and 14: The view of Anna below the stage plan – she looks as if she is almost profile rather than facing the LFC.
**[This maybe an issue with the ipad mini - Anna definitely looks like she is facing the corner to me, especially compared to Rose facing the side wall. Do you want to cheat and turn Anna a little more to the front, or leave her as is?]**

- [x] P13:	Not sure what you mean by ‘room numbering systems’.
**[Do you think this should be changed to "corner and wall numbering systems"? The title would have to be changed on page 125 to "Corner and Wall Numbering" as it wouldn't fit with Direction Signs as well.]**

- [x] P16:	Up till here it appears as if you have set up a ‘code’ by dressing  males (Ben) in black tights. On this page this code seems to have got forgotten apart from upstage right. Suggest you reinstate it or have all of them in pink tights.
**[I am totally perplexed by this comment.  Perhaps on the iPad mini the rose coloured leotard looks black? Am I missing something? The layout of these pages have changed since this original draft. The DanceForms figures are now slightly bigger, so perhaps this is no longer an issue? Should I follow up with Liz on this, or not worry about it? I could always send her a screen shot of the updated page?]**

- [x] P16:	Here again the figures in the stage plans are very hard to figure out on my ipad mini.  Applies to all later similar pages.  My feeling is that they would be better replaced by BMN direction signs, filled in for the ladies and open for the males.
**[We have changed these to x's, so I don't think this is an issue any longer.]**

- [x] P16:	All BMN examples with hands hanging level at their lowest possible placement: the level signs should be positioned in the middle of the waist to knee space.
**[This is a picky one, but easy enough for me to change in Adobe Illustrator. I didn't realize that this position should be halfway between waist and knee. Good to be reminded of the convention.]**

- [x] P34:	The sideways tick is too small to read properly in all of the examples – OK when magnified but would be better if they were slightly bigger if possible in the default form.  (Remember I am on ipad mini) Also applies to P 36 and to the diagonal travel examples P 42 and 45. 
**[This is something I can fix in Adobe Illustrator. I can make the travel signs under the stage plans a little bigger on all four of these pages. Under the big stage plan, is it okay for the summary travel pattern to be bigger than the size defined by the ticks on the location signs?]**

- [x] P40 and 41: The angle of the outstretched arm in the first 2 dance forms figures (Fwd right & fwd left) is not quite the same as the corresponding angle of the travel sign – can they be moved outwards a little so the two things match?
**[Is this something you are willing to fix? It looks a little better in our updated version with the gloves. However, take a look and see what you think.]**

- [x] P47 Review 3.1: When attempting to drag the labels to the buttons there is a tendency for the  page to move left or right rather than the label. 
**[I see what Liz means. However, if the reader presses and waits, then drags the label, this issue goes away. Should this be something we explain somewhere? Please try it out and let me know your thoughts?]**

- [x] P47 Question 4 of 9: Suggest you reword the question to make the task more obvious, e,g. “Drag the labels to the buttons so that the location, direction and travel signs are placed in the correct sequence to match the travel pattern on the stage plan."
Also applied to similar egs later.
**[In the old version of the book we had: "Drag the labels to the buttons to order the location, direction, and travel signs to match the travel pattern on the stage plan."
We now have: "Drag the labels to the buttons to create the sequence of location and travel signs that match the blue arrow on the stage plan."
Liz's wording is too long to fit on one line and I can't take it to a smaller font as it is already at the smallest font for the review questions. Making it two lines would screw up the layout of all the questions for Review 3.1. Do you think our updated version is inline with Liz's suggested rewording?]**

- [x] P47 Question 8 & 9: Suggest a different colour for the travel sign in the stage plan to help distinguish it  from the ‘dotted line’ for the R Half. Why not stick to red as in previous e.g.?
**[It seems the colour scheme for the travel signs isn't obvious to Liz. I could help the situation by greying out the dotted lines for these two examples. What do you think?]**

**Comment by rsryman** [comment]
Re P12, 13, and 14: Perhaps an issue on the mini. Leave Anna as is; her arabesque is definitely angled compared to Rose who is clearly facing a side wall.

P13:	Re ‘room numbering systems’ - this wording is also used on p. 118 and 125. We tried to use something generic because the 3 schools use different wording. Our usage is explained right on p. 13, with reference to an illustrated explanation on p. 125. Your suggested wording is cumbersome but I can't think of anything better, so I suggest that we leave this as is.

p. 16: She will see the updated page in the full iBook. Hasn't she downloaded it? And as we discussed, this series is not guaranteed for the iPad mini. I don't think you should tweak any of the signs to look better on the mini (re p. 34, etc.).

p. 16 Yes, in MacBenesh I place hands en bas in the middle of the 2nd space.

p. 34 See comment re p. 16.

p. 40-41 This didn't bother anyone else. Maybe more apparent on the mini? This would require changes to 19 animations (pp. 38-41, 43-44). I can redo these if you feel strongly but it's a lot of work for something that seems irrelevant. (To be really picky but technically correct, I would point out that "diagonal" in BMN does not literally mean 45° since the depth of the diagonal path can be more or less shallow, conditioned by the start and end location, yes?) The important point here is that the animation should clearly illustrate the basic theory, so if you feel a change would be clearer, I will tweak the arm angle. Also, you will need to shift the position of some animations (e.g., p. 43 shift first animation sightly left to align R arm with travel sign).

p. 47 I don't have a problem, but this should work fine with a bit of trial-and-error. A delicate balance between the tendency to over-explain versus letting the user play and discover. Less can be more. I like our revised wording. Liz made her suggestion without knowing our constraints, but I think our version works well. Re the blue arrow, Liz didn't clue in that we were using the colour scheme we set up re directions. Perhaps this is only a problem on the mini? Leave as is since no one else had a problem?

**Comment by rsryman** [comment]
I have uploaded new files for travel forward-right re pages 39-41, with the right arm slightly more open (shoulder rotated y=10), in line with the slant of the travel arrow. If these are OK I'll continue updating.

**Comment by rsryman** [comment]
I have uploaded 16 new files into Dropbox > For Robyn > CH3S1_p#(a-d)NEW

The files are named for the NEW page numbers, examples a-d:
P. 40: 4 jpg
P. 41: 4 m4v
P. 43: 4 jpg
p. 44: 4 mov

For the 2 animations on p. 39, use p40aNEW and p44cNEW

**Comment by rsryman** [comment]
Rhonda tasks:

- [ ] pp. 12-14 update Anna jpeg to look more angled
- [ ] p. 41 upload to Dropbox CH3S1_941aNew.m4v

Robyn tasks:
- [ ] pp. 13, 118, 125 delete the word "room"; and relink these 3 page 
- [ ] p. 16 send screen shot to Liz (we clearly see Ben in black, rose in burgundy; re hands beside thighs, lower level signs to middle of second space here and globally (e.g., Ben walking, etc.)
- [ ] pp. 30, 32, 34, 36, 42, 45 enlarge travel arrows below left stage plans; also under larger plan on right on pp. 34, 36, 45
- [ ] p. 39 (2) 40 (4), 41 (4), 43 (4), 44 (4) use updated images and animations
- [ ] Review intro pp. 17, 46, 63, 98, 112 add TIP box (like p. 20). TIP: To drag buttons in these Review questions, tap and HOLD until the button activates before you try to move it. (Email Liz to thank her for her comment, send screen shots, and tell her that we added this Tip in case she downloads the new book.)
- [ ] p. 47 Questions 8 & 9 lighten the vertical dotted black lines on the stage plan to clarify the blue travel arrow

**Comment by rsryman** [comment]
Re pp.12-14, please see new image of Anna in Dropbox > For Robyn > Book4_AnnaP12
I checked the Inspector to find that the image was called 3rdArabesqueUpstageR+.jpg. We used Basic Positions from Book 1. The figure in the uploaded file is based on the Russian 3rd arabesque but angled more to the front (135° -> 150°). If this is OK, please check of the item above.
