### ISSUE TITLE
Feedback - Anuschka

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#80]
Below is the feedback from Anuschka.
I emailed her with my reaction to her comments. I have put these in bold under Anuschka's comments. I haven't heard back from her yet - 11:30 am Thursday January 4th.

- [x] I’m about 1/2 way through.  It is fantastic!! What an achievement!

- [x] I am almost through – but not quite. I plan to finish tomorrow.
So far I have the following:
2.2 location puzzle – I find the difference between downstage and mid downstage difficult to see – not sure if that is solvable.
**Location Puzzle - unfortunately in Benesh there is not much room on the location sign to show much difference between downstage and mid-downstage. For the puzzle, we could make the location signs bigger to make the difference more noticeable, but then the reader doesn't get practice seeing the subtle differences of the actual sized location signs and how they need to be read in relation to other location signs. It makes the puzzle more challenging. Did you find you were unable to solve the puzzle? How strongly do you feel about us changing the puzzle?**

- [x] Music wasn’t working until page 78 – not sure if that was just my download……after that it seemed fine.
**There is no music until page 78. Up to that point there isn't any stave notation with time signatures, so providing music didn't seem relevant. Should we mention this somewhere?**

- [x] Page 66 – not sure what the bottom animation is for?
**Pages 66 - 69: There are two questions on each page. On each page, the first question relates to the top animation and the second question relates to the bottom animation.**
**Rhonda, do you think we need to state this somewhere?**

- [x] Page 99 – choice #1 – must really be rusty – can’t figure out what’s wrong?? Help! 
**Page 99 question 7 of 8 option #1: The double brackets are missing. When you have a curved path of travel you have to use double brackets to enclose the location and travel information to show the duration of the curved travel.**

**Comment by rsryman** [comment]
Any reply form AR re the Location Puzzle? I think we need to keep location sign size consistent, as is.

Where could we put a note re no music to p. 78? Leave as is, since no one else had a problem with this?

p. 66 The labels clearly say "Question 1 of 2." and "Question 2 of 2." If they don't notice that here, they likely won't remember it from an instruction on p. 63, so leave as is.

p. 99 I'm rethinking the idea of adding an answer sheet in the Appendix. In addition to being too much work, I think it's not necessary. We have said that the series to be used as a supplement to workshops, etc., rather than as a means of learning BMN in isolation. No language can be learned without human contact, so readers should be consulting a teacher or at least a fellow student.

**Comment by rsryman** [comment]
Robyn tasks:
- [ ] re animations in silence versus music; p. 20 TIP note updated; p. 70: footer note updated
- [ ] pp. 66-69 instruction updated. Preview on the iPad to check if the formatting is OK
- [ ] p. 99 Question 7 broken into 4 multiple choice questions with larger BMN staves; on 4th example change right foot step into 2nd to left foot; also update p. 98 "eight" -> "eleven"

**Comment by rryman** [comment]
Note: Anuschka didn't have strong feeling about updating the Location Puzzle, so we are keeping it as is.

**Comment by rryman** [comment]
Anuschka's response to breaking Page 99 Question 7 into 4 multiple choice questions:
"That seems like a really good solution. I like it when the testing includes further learning. It’s likely the people who use these books won’t have lots of notation background so the ‘help’ included in the choices makes a difference. Great idea!"
