### ISSUE TITLE
Feedback - Ros

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#81]
Ros still plans to read through Chapters 1 and 2 and send us feedback.
Below are her comments starting at Chapter 3 (though she obviously couldn't resist doing "location puzzle" on page 19 :)

My comments are in bold below Ros' feedback:

- [x] Absolutely love all the animations and colours, red feet and pointing gloves/hands. Very clear now, and really careful detailed information. This book is PhD level presentation and beyond. Your minds are sooooo crystal clear and organised. Nothing is left out! (I'm really envious!)

- [x] p19: Puzzle is GREAT.

- [x] p21: states that the general travel sign does not show direction faced. You've put this in italics, and clearly state on the next page in italics that the 'travel sign does show direction'. I'm being picky, but when I read the two pages straight through I felt a 'bone to pick' coming on. 
In terms of crystal clarity, it might stop people like me picking bones if I read on page 21 that the 'general travel sign does not show direction faced whereas the individual travel sign does.'
**[We have plenty of room on this page. We could add something in brackets after the first sentence. What do you think?]**

- [x] p23: LOVE it! Gloves and colours, super clear. :)

- [x] p30: perspective on first example had me wondering. It looked as if she was going forward in a diagonal path to downstage right. p32 example worked better to show the perspective because she came directly towards us first, so when she moved into the distance it was clear to see use of perspective without confusion. (I'm reading it like a novice and deliberately (or easily!) falling into errors and slips that could happen as such). Could the perspective angles used be slightly less acute maybe? Just a gentle slant? Do you need to show perspective at all??? Is that going too far ahead for the reader? Do they need to be trained to read like that at this stage or will it confuse them more? 
Just my thoughts :)
**[This one is your domain.]**

- [x] p39 & 44: SUPER clear explanation and excellent animations. LOVED them :)

- [x] p41:There's an asterisk which is not explained on this page and not next to an explanatory page either: 'facing front throughout*'
**[I will delete the asterisk.]**

- [x] p48 Review Q 1 of 3.2
The red arrow is not at the bottom of the page, to advance the page.
**[There are no further questions on this page so there is no advancing arrow. Do we need to explain things differently (more thoroughly) in the introduction to each review?]**

- [x] p51: List of contents links - I couldn't get the first one (Entrance and Exits) to work unless I clicked on the underlining, not the words.
**[I have noticed that it is often hard to get the first link in these bulleted list to work. I think it might be because I have cheated and made the space above the list smaller, i.e., 9 points instead of the 18 or 20 points like the rest of the text. Do you think I should use the proper spacing before all bulleted lists to eliminate this problem? It will mean a wider space between the text and the bulleted lists - a trade off between looks and ease of use.]**

- [x] p55-58: Loved the different colours for the animations.

- [x] p60/97: LOVED the example, really nice combination of music for the animation.

- [x] p64: Review Questions for 4.1 were great - not as easy as they seem! 

- [x] p82 "i-Box": The tiniest detail, but may be important for consistency. I suddenly noticed in many of the Information boxes that so diligently explain the steps: 
Sometimes there's only a full stop after 'Count 2'. for example, and mostly there is a colon. So it sometimes reads
Count 1:
Count 2.
Count 3:
Maybe they all need to be colons? Or full stops/periods?
(This is a real picky proofreading thingy - but my friend's book was not approved by one publishing house until all these kinds of points were corrected! I know Apple will not notice or worry about these, but the extremely high quality detail of your work deserves these 'i's dotted and t's crossed', I reckon.)
**[I will go through all the "i-box" text and fix this. Should I also be putting a colon after the Anacrusis count so it is also consistent, or is the period in this case okay?]**

- [x] p85: lovely music :)

- [x] p92: very nice idea to adapt the en face example to face the corners :)

- [x] p98 states bars 3-10 for the repeat​, but there seems to be a missing bar line on the first stave - only 9 bars in total I think I see....
**[Is Ros just reading this incorrectly, or do I have it notated in a confusing manner? Perhaps the dotted bar line is confusing? However, I think the dotted bar line is necessary to show when the dancer starts travelling straight.]**

- [x] p99 Q5: says 'through the music action'. What is music action? maybe leave the 'action' off end of sentence? Or use 'through the bar'  ???
**[Should we reword this?]**

- [x] p99 Q7 - I wanted the errors explaining somewhere. Also, in my humble opinion, the 'correct' one has no step or slide line to beat one of bar 1. I wondered if two pairs of questions here would be more consistent with the level of difficulty in this review? Maybe pick the 'wrong' one and say why, for each pair? It's easy to press buttons and get the right one without knowing anything!
**[Anuschka had trouble with this question as well. She couldn't find the error in option 1. I don't really understand what Ros means about the "no step or slide line to beat one of bar 1" do you? I also don't know how to redo this question the way Ros is suggesting. Perhaps we should consider just taking it out?]**

- [x] p99: Loved Q8 :)

- [x] p102: there is no 'Congratulations' after finishing these three Q's :(
**[The three Q's are on three separate pages, i.e., three separate review questions with only 1 question in each. It clearly gives different review numbers at the top of the page, but it seems to confuse readers to have different sorts of questions in the reviews. I can't do anything about not being able to embed animations in the review widget so that all questions have the same format. As I mentioned above - perhaps we have to consider explaining it in the introduction to each Review section?]**

- [x] p103: Well chpt 6 was a lot of fun to read :)

- [x] p104: was hard for me to 'get' with the music. The steps are cross phrased rather than in 4s, and music is not clearly showing the beat right from the anacrusis.  Watched this lots of times and figured it out, but it wasn't clear for me. The music also finishes 'before the end' of the phrase. This feels unsatisfactory, as well as incorrect, as I 'need' one more bar of music, but there's two bars 'left over' of notation - it finishes on bar 14 in notation.
Could it be a straight 16 bar phrase both musically and notation-wise with a strong one bar intro to make it clear? Or two bars intro of music and start the dancer on bar three so they both finish 'together' ???
Do the steps need to be this complex (sorreee, I know it's exhausting writing the notation for these examples and getting it animated...) or would walks or even just changements and soubresauts do it?
**[This one is also your domain.]**

- [x] p105 & 106 work PERFECTLY with the animation and music. Loved them both :)

- [x] p107: music again was hard to feel the beat immediately because of the anacrusis style he used. It was fuzzy for me on playback. Maybe a paused upbeat note alone as an anacrusis would signal the first beat better ( for me)
**[This one is also your domain.]**

- [x] LOVED p108, excellent explanation and love the extra boxes of info - super detail LOVED the colours changing on the dancer and shown on the arrows, and clear Red RF. Exquisite teaching here, superlative :)))) wish I could teach like this :)
(It was so well explained that it caused me to wonder how we notate/show a reverse version of this sequence whereby the RF goes back first? I guess it would be shown in stave...)
**[Ros has lost me on this one - I don't know what she means. We have the reverse fully notated on the next page so it seems pretty obvious how to notate this step in reverse.]**

- [x] p113 Review 6.1: great Qs - not as easy as it looks!  LOVE it!

- [x] p113,review 6.1 Q 14:
I was confused by 'left foot crossed over' on the label, as this is underneath a step with RF to R; then the LF slides diagonally forward across.  This may be a spacing issue? can the button move over a bit more to the right??
**[I can move the third button over to the right more. The "slide forward-right label" should fit under the button for the "left foot crossed over".]** 

- [x] p120: I checked all the links on p120, so when I clicked the 'On the location' red link it went nicely to p 121. Then I clicked at the bottom left 'back to p120' curved arrow link and it kept taking me to p128, or then p118. Never p120. Maybe it's my MacBook. Anyway, it did the same for all the other links back to p120. They all went to p118 although they'd all gone nicely from p120 to the appropriate red titled link ( p122, 123,124).
**[I suspect this is a problem with the version of iBooks Ros is using on her MacBook. It is the version where the "back to" buttons didn't work properly. We do have a FYI on page 3 stating the know problems, but Ros wouldn't have read it yet. I guess Ros didn't clue into using the red navigation link to the "Interactive Stage Plan" in the top right corner to get her back to page 120. We haven't explained the linking system we used in Book 4. Do we need to do so? If so, do we add another FYI on page 3?]** 

- [x] Many thanks for this great chance to re-learn my Benesh :)

- [x] Ros' Puzzle Idea based on the game "match three":
I imagined a grid of travel signs only, all mixed up. The direction sign is stated/shown above it or to the right. You zap all the travel signs that do NOT show facing front/downstage. If you zap a wrong one, it doesn't disappear and you get a penalty point. Or something. So you should end up with a mixed grid of all the possible travel signs for facing front. Or another grid where the signs are only correct if you are facing upstage. Or for facing a corner. There should also be a time limit on these, so that if you don't find them within the three minutes, it's Game Over :)
**[I thanked Ros for her idea, but told her we couldn't implement it for this book. I told her we would keep it in mind if we ever did a book of reviews and puzzles based on books 1-4.]**

**Comment by rsryman** [comment]
p. 21 Add para at bottom of page: Each _general travel_ sign (which shows the **path** but not the **direction** faced during travel) may be divided into [OR is the basis for] four basic _travel_ signs, which incorporate both the **path** and the **direction** faced during travel. OR SIMPLY
Each _general travel_ sign may be divided into four basic _travel_ signs, which incorporate both the **path** and the **direction** faced during travel.

p. 30: I could explain to Ros: This book challenged us to work within the particular 3-D algorithms of DanceForms, i.e., distortions caused by the narrowing "vanishing point" as the figure moves farther from the viewer. Rhonda did what she could to minimize this, and we can only hope that  readers will gradually get used to this perspective drawing convention, but your comment has spurred us to add an FYI note on p. 29. Does this address your concern?

ROBYN TO REFINE WORDING: To this point, DanceForms animations have shown an overhead view. From here on, the figure is presented from behind (upstage) as he or she travels around the stage. DanceForms uses the conventions of linear perspective developed in Renaissance Italy by the artist Giotto di Bondone (1277-1337). Perspective is shown via parallel lines that converge to a single point known as the "vanishing point."  In a DanceForms animation viewed from behind (upstage), the performing area therefore appears narrower downstage than upstage and the figure appears smaller as he or she moves farther from the viewer.

p. 48 I think the reader will figure out that you just need to swipe

p. 51 To be decided together?

p. 82 Yes, do a global search on "Count" to fix all.

p. 99 Q5 I think we mean "…on each couru action." or "…on each couru sequence."
p. 99 Q7 If the foot takes the weight past the pointe tendue position, a step line is needed (which is the intention). To be discussed re explanations, perhaps in an Appendix? That would address Anuschka's problem. Only for certain questions -- but which? Ros's suggestion means a lot more work, not sure if it's warranted.

p. 102 To be discussed? More explanations just add words to an already verbose page.

p. 104 Ros thinks too rigidly in 4's! I suggest an addition to the i-box text: The dancer performs a series…rectangular pattern: three toward downstage, four toward stage right, three toward upstage, and four toward stage left.

p. 107 I'll look at Richard's site again just in case there is another slow 3/4. If not, I think it's ok as is, since it didn't bother other readers and we don't have wide musical options. 

p. 108 Yes, no action needed.

p. 129 re p. 3 To be discussed?

**Comment by rsryman** [comment]
Rhonda tasks:
p. 30: Email to  Ros: This book challenged us to work within the particular 3-D algorithms of DanceForms, i.e., distortions caused by the narrowing "vanishing point" as the figure moves farther from the viewer. Rhonda did what she could to minimize this, and we can only hope that readers will gradually get used to this perspective drawing convention, but your comment has spurred us to add an FYI note on p. 29. Does this address your concern?

Robyn tasks:
- [ ] p. 21 at bottom: Each _general_ travel sign (which shows the **path** but not the **direction** faced during travel) is the basis for four basic _travel_ signs, which incorporate both the **path** and the **direction** faced during travel.
- [ ] p. 29 FIY: FYI: To this point, DanceForms animations have shown an overhead view. From here on, the figure is presented from behind (upstage) as he or she travels around the stage. DanceForms uses the conventions of linear perspective developed in Renaissance Italy. Perspective is shown via parallel lines that converge to a single point known as the "vanishing point." In a DanceForms animation viewed from behind (upstage), the performing area therefore appears narrower downstage than upstage and the figure appears smaller as he or she moves farther from the viewer, as on the next page.
- [ ] p. 41 delete asterisk after "throughout."
- [ ] p. 48 & p. 102 email Ros to explain how reviews work and ask whether it warrants an explanation in each Review intro page
- [ ] p. 51 global change to all bulleted lists: 18 pt space to help user find sweet spot on top link (and refine layout as needed) 
- [ ] p. 82 i-box global search re i-box to add colon after "Counts" (also re all Anacrusis)
- [ ] p. 98 email explanation to Ros
- [ ] p. 99 Q 5 of 8 update instruction: "…on each couru sequence."
+ Q7 of 8 See Anuschka comments; send Ros and Anuschka screen shots of the updated pages
When there is more than 1 Question in a Review Section (e.g. Review 3.1), you will see Question 1 of "x" and a red arrow at the bottom of the Review window. When you complete the final question in that Review Section, you will the number of Answers Correct, and a Congratulations message if successfully complete that Review Section. Then you must tap or swipe to move to the next page. If the Review Section contains one question only (e.g., Review 3.2) you will not see a red arrow or a Congratulations message.

**Comment by rsryman** [comment]
Rhonda tasks:
Pursue getting the series reviewed in the Gazette.
- [ ] p. 104 add FYI box explaining the music: starts on silent count 2 after sounded count 1; then cross-phrased; we wanted a musical challenge other than straight counting (If changed, this would also affect pp 78-79 and Review 6.3 p. 115) Email Ros to explain that there could be an intro bar (not 2) but we decided not to include intro bars to save room on the wider notation of long sequences; there really is NOT 2 bars of extra notation.
- [ ] p. 107 & 116 update animations to start on B 1 ct 1 and end at end of B 4 ct 3 (bigger steps on each couru; email Ros that we have limited music excerpts and we couldn't find another appropriate clip; send her the updated m4v files to "approve")
- [ ] p. 108 "it caused me to wonder how we notate/show a reverse version of this sequence whereby the RF goes back first? I guess it would be shown in stave..." Email Ros to explain what she means. Instead of a reverse on the other side repeat, do you want a reverse on the same side repeat? You would use different repeat signs around the phrase and different below stave travel signs to show a different shaped path (Bars 5-8 retrace the first "v" shape re Bars 1-4), right? Are you asking if we assume the passé on the pickup to Bar 5, or must we show the passé in the empty stave for clarity? We would put it in, but most readers would probably do it automatically.

Robyn tasks:
- [ ] p. 104 add to the i-box text: The dancer performs a series…rectangular pattern: three toward downstage, four toward stage right, three toward upstage, and four toward stage left.
- [ ] p. 113 Review 6.1 Question 14: move 3rd button a bit to the right under the diagonal cross-out sign

**Comment by rryman** [comment]
Robyn Tasks:

- [ ] p. 104 add FYI box: In this sequence, we wanted to create an unconventional phrasing correlated to the geometric pattern rather than the musical structure. The music starts with a chord on count 1 of the Intro Bar (not notated). The first spring lands on count 2 (in silence), which is the pickup to Bar 1 count 1. The musical phrase comprises 14 bars of Galop 2/4, but the dance sequence is cross-phrased to correlate with the number of chassé, coupé sauté actions used to create the rectangular pattern: three toward downstage, four toward stage right, three toward upstage, and four toward stage left.

- [ ] p. 107 & 116 add updated animations

**Comment by rryman** [comment]
Rhonda Tasks:

- [ ] Check animations for page 116 and update as necessary.
